### ISSUE TITLE
Creating new workout

### ISSUE THREAD

**Issue by Shivneel7** [Betovef/fitness-tracker#11]
I added the workout searchbar:
![image](https://user-images.githubusercontent.com/18388474/141761591-e4c0602c-784d-4f6a-b6e9-8148f8b68668.png)
![image](https://user-images.githubusercontent.com/18388474/141761615-43838f08-456e-41e1-81a0-adef22f27109.png)
However the button does nothing.

TODO: make it so when you click new workout it makes input fields appear that asks for: date, sets, reps. We could also have those textboxes already visible and ready to have values inserted in and then the add workout button will just add the values to all relevant databases (relevant databases are: sets, routine). 

Possible alternative: maybe we add a workout to routine, and then we can just edit the workout to add new sets?

**Comment by Betovef** [comment]
![image](https://user-images.githubusercontent.com/56320553/141827905-a60d6987-d788-4e96-97f3-086a171a7de2.png)
I'm still thinking in how to display this but this is the idea I have so far. We can work on this design later if you want since it may be the most important part of the app in terms of visualization for demo (phase 3)

**Comment by Betovef** [comment]
So far the list is looking good for searching for exercises

**Comment by Betovef** [comment]
Also, sorry if I am not using the work exercise and workout correctly I need to go back to check the schema bc I keep forgetting which represents what lol

**Comment by Betovef** [comment]
Update on things to do after new changes:
- [ ]  Add "completed" button 
- [ ]  Save data to database 
- [ ]  Integrate the search by category

**Comment by Betovef** [comment]
Update:
- Everytime time the user login we check if there is an existing training session with status = 0, if there is one we use that as the session to insert workouts, if not we create a new session (insert a new session)
We finished this issue essential so I am going to close it and I will open another one with the current things to be done in this page
