### ISSUE TITLE
View Progress and edit workouts

### ISSUE THREAD

**Issue by Shivneel7** [Betovef/fitness-tracker#12]
Show a graph of progress and allow a user to search their own old workouts.

 Perhaps they can also edit workouts here (for example changing the r_status (shown below) to be 1 for complete)
![image](https://user-images.githubusercontent.com/18388474/141762242-3f64dc51-7de1-4476-b0c3-b0b2904522e5.png)

This might also be where adding sets goes.

**Comment by Betovef** [comment]
![image](https://user-images.githubusercontent.com/56320553/142075250-62071721-1af5-4ff9-8171-23a4bbdb5d4a.png)
This is the idea that I have for the View Progress so far I added your suggestion to display the data as well, any suggestions?

**Comment by Shivneel7** [comment]
Under the graph, show SELECT * as a table
