### ISSUE TITLE
**Fix database**

### ISSUE THREAD

**Issue by Betovef** [Betovef/fitness-tracker#6]
The data in the database gets deleted every time the application restarts
*Reproduce:* 
1. Register some users 
2. Login with the users registered to verify they are on the database
3. Restart the app
4. Check that the data has been wiped out

**Comment by Shivneel7** [comment]
I think we could fix this if we only run init_db() from the db.py if the data.db does not already exist since hte schema.sql file starts by dropping all the tables.

**Comment by Betovef** [comment]
Added CREATE TABLE IF NOT EXISTS to schema.sql statements
